apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  annotations:
    run.googleapis.com/ingress: all
    run.googleapis.com/ingress-status: all
    run.googleapis.com/urls: '["https://agent-data-1042559846495.asia-southeast1.run.app","https://agent-data-k4ttla6eeq-as.a.run.app"]'
  labels:
    cloud.googleapis.com/location: asia-southeast1
    run.googleapis.com/satisfiesPzs: 'true'
  name: agent-data
  namespace: '1042559846495'
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/maxScale: '40'
        run.googleapis.com/client-name: gcloud
        run.googleapis.com/client-version: 517.0.0
        run.googleapis.com/startup-cpu-boost: 'true'
      labels:
        client.knative.dev/nonce: kobrxfzetq
        run.googleapis.com/startupProbeType: Default
    spec:
      containerConcurrency: 80
      containers:
      - image: gcr.io/chatgpt-db-project/agent-data:latest
        ports:
        - containerPort: 8080
          name: http1
        resources:
          limits:
            cpu: '1'
            memory: 512Mi
        startupProbe:
          failureThreshold: 1
          periodSeconds: 240
          tcpSocket:
            port: 8080
          timeoutSeconds: 240
      serviceAccountName: gemini-service-account@chatgpt-db-project.iam.gserviceaccount.com
      timeoutSeconds: 300
  traffic:
  - latestRevision: true
    percent: 100
