repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0 # Use a recent, stable version
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files

-   repo: https://github.com/psf/black
    rev: 24.4.2 # Use a recent, stable version
    hooks:
    -   id: black
        args: [--line-length=120]

-   repo: https://github.com/PyCQA/flake8
    rev: 7.0.0 # Use a recent, stable version
    hooks:
    -   id: flake8
        args:
        -   "--max-line-length=120"
        -   "--ignore=E203,E501,W503" # E203: whitespace before ':', E501: line too long (handled by black), W503: line break before binary operator
        exclude: ^(venv/|\.venv/|__pycache__/|\.git/|\.tox/|build/|dist/)

-   repo: https://github.com/PyCQA/bandit
    rev: 1.7.10
    hooks:
    -   id: bandit
        args: [-r, --severity-level, high]
        exclude: ^(venv/|\.venv/|__pycache__/|\.git/|\.tox/|build/|dist/|tests/|\.cursor/|functions/|containers/|Documents/)

-   repo: local
    hooks:
    -   id: pycompile-check
        name: Python Compile Check
        entry: python -m py_compile
        language: system
        types: [python]
        pass_filenames: true # Pass all staged .py files to py_compile
        # Consider `args: [-x, path/to/exclude]` if needed, but py_compile usually handles this well.

    -   id: check-fixture-drift
        name: Check Fixture Drift
        entry: sh -c 'cd "/Users/nmhuyen/Documents/Manual Deploy/mpc_back_end_for_agents" && PYTHONPATH=. exec ./scripts/run_drift_check.sh'
        language: system
        always_run: true
        pass_filenames: false
