steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/google-docs-updater', '.']
    timeout: '1200s'
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/google-docs-updater']
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['run', 'deploy', 'google-docs-updater', '--image', 'gcr.io/$PROJECT_ID/google-docs-updater', '--region', 'us-central1', '--platform', 'managed']
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['app', 'versions', 'migrate', '--service', 'default', '--to', 'stable']
    entrypoint: 'bash'

images:
  - 'gcr.io/$PROJECT_ID/google-docs-updater'

options:
  logging: CLOUD_LOGGING_ONLY

