steps:
  # 1. Build Docker image
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "build"
      - "-t"
      - "gcr.io/$PROJECT_ID/dummy-function:latest"
      - "."

  # 2. Push Docker image
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "push"
      - "gcr.io/$PROJECT_ID/dummy-function:latest"

  # 3. Deploy Cloud Run (Chỉ update image, không thay đổi Terraform)
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        gcloud run deploy dummy-function         --image=gcr.io/$PROJECT_ID/dummy-function:latest         --region=asia-southeast1         --platform=managed         --allow-unauthenticated
