name: Deploy Dummy Workflow
# CLI153.2: Fixed CI for production deployment with proper secret validation

on:
  push:
    branches: [main, test]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_PAT }}
          submodules: 'recursive'

      - name: Determine Project ID
        id: get_project
        run: |
          if [[ "${{ github.ref_name }}" == "main" ]]; then
            echo "project_id=${{ secrets.PROJECT_ID }}" >> $GITHUB_OUTPUT
          else
            echo "project_id=${{ secrets.PROJECT_ID_TEST }}" >> $GITHUB_OUTPUT
          fi

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}
          token_format: 'access_token'

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ steps.get_project.outputs.project_id }}

      - name: Verify Authentication
        run: |
          echo "🔐 Verifying GCP authentication..."
          gcloud auth list --filter=status:ACTIVE --format="value(account)" | head -1
          echo "📋 Using project: ${{ steps.get_project.outputs.project_id }}"
          gcloud config set project ${{ steps.get_project.outputs.project_id }}

      - name: Deploy dummy workflow
        run: |
          echo "🚀 Deploying dummy workflow..."

          # Check if dummy workflow exists
          if [ ! -f "workflows/dummy_workflow.yaml" ]; then
            echo "⚠️  No dummy_workflow.yaml found, skipping deployment"
            exit 0
          fi

          # Validate workflow file
          if ! python3 -c "import yaml; yaml.safe_load(open('workflows/dummy_workflow.yaml'))" 2>/dev/null; then
            echo "❌ Invalid YAML in dummy_workflow.yaml, skipping..."
            exit 1
          fi

          # Deploy with retry logic
          for attempt in 1 2 3; do
            echo "🔄 Deploy attempt $attempt..."
            if gcloud workflows deploy dummy-workflow \
              --source=workflows/dummy_workflow.yaml \
              --location=asia-southeast1 \
              --project=${{ steps.get_project.outputs.project_id }}; then
              echo "✅ Successfully deployed dummy workflow"
              break
            else
              echo "❌ Deploy attempt $attempt failed"
              if [ $attempt -eq 3 ]; then
                echo "❌ All deploy attempts failed"
                exit 1
              fi
              sleep 10
            fi
          done

      - name: Verify deployment
        run: |
          echo "🔍 Verifying deployment..."
          gcloud workflows describe dummy-workflow --location=asia-southeast1 --project=${{ steps.get_project.outputs.project_id }} --format="value(name,state)"
