name: Authentication Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  auth-test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2
      with:
        workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
        service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v2

    - name: Test authentication
      run: |
        echo "Testing GCP authentication..."
        gcloud auth list
        gcloud config list project
        echo "Authentication test completed successfully!"

    - name: Verify project access
      run: |
        echo "Verifying project access..."
        gcloud projects list --limit=5
        echo "Project verification completed!"
