name: Basic Test

on:
  push:
    branches: [ "main", "test" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        if [ -f requirements-dev.txt ]; then pip install -r requirements-dev.txt; fi
        
    - name: Run basic tests
      run: |
        if [ -f pytest.ini ]; then
          python -m pytest tests/ -v --tb=short
        else
          echo "No pytest.ini found, running basic Python syntax check"
          python -m py_compile *.py || echo "No Python files to compile in root"
        fi
