name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    name: Code Quality & Format
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install linting tools
        run: |
          python -m pip install --upgrade pip
          pip install black isort flake8

      - name: Run Black
        run: black --check --diff .
        continue-on-error: true

      - name: Run isort  
        run: isort --check-only --diff .
        continue-on-error: true

      - name: Run flake8
        run: flake8 . --count --statistics
        continue-on-error: true

      - name: Summary
        run: echo "Lint checks completed"
