name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-in-docker:
    name: Run Tests in a Clean Docker Environment
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      
      - name: Build Test Image
        run: docker build -t agent-data-test-local -f Dockerfile.test .
      
      - name: Test Docker Environment
        run: |
          echo "Testing Docker environment..."
          docker run --name test-env-check agent-data-test-local python --version
          docker run --name test-pytest-check agent-data-test-local pytest --version
          docker rm test-env-check test-pytest-check || true
      
      - name: Run Pytest and Extract Report
        run: |
          docker run --name test-container agent-data-test-local pytest --json-report --json-report-file=.report.json -m "unit and not slow" || true
          docker cp test-container:/app/.report.json . || echo "Failed to copy report"
      
      - name: Verify Test Count From Report
        run: |
          echo "Analyzing test report from Docker run..."
          python3 scripts/verify_test_count.py 