name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-in-docker:
    name: Run Tests in a Clean Docker Environment
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Build Test Image
        uses: docker/build-push-action@v5
        id: build
        with:
          context: .
          file: Dockerfile.test
          tags: agent-data-test-local
          load: true
          platforms: linux/amd64
          provenance: false
          cache-from: type=gha
          cache-to: type=gha,mode=max
      
      - name: Generate Baseline Tests Artifact
        run: |
          echo "Generating baseline test collection and SHA..."
          docker run --rm agent-data-test-local pytest --collect-only -q --timeout=60 --override-ini="addopts=-m 'unit and not slow'" > collected_tests.txt
          sha256sum collected_tests.txt > collected_tests.sha256
          echo "TEST_COUNT=$(wc -l < collected_tests.txt)" >> $GITHUB_ENV
          echo "Generated $(wc -l < collected_tests.txt) test entries"
          echo "SHA256: $(cat collected_tests.sha256)"
      
      - name: Upload Test Collection Artifact
        uses: actions/upload-artifact@v4
        with:
          name: collected-tests
          path: |
            collected_tests.txt
            collected_tests.sha256
      
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@0.32.0
        with:
          image-ref: agent-data-test-local
          format: 'sarif'
          output: 'trivy-results.sarif'
          exit-code: '0'
          ignore-unfixed: 'true'
          severity: 'HIGH,CRITICAL'
      
      - name: Test Docker Environment
        run: |
          echo "Testing Docker environment..."
          docker run --rm agent-data-test-local python --version
          docker run --rm agent-data-test-local pytest --version
          docker run --rm agent-data-test-local ls -la
          docker run --rm agent-data-test-local python -c "import sys; print(sys.path)"
      
      - name: Run Pytest and Extract Report
        run: |
          set -e
          docker run --name test-container agent-data-test-local pytest --json-report --json-report-file=.report.json -m "unit and not slow" --tb=short -v || echo "Pytest failed but continuing..."
          docker cp test-container:/app/.report.json . || echo "Failed to copy report"
          docker rm test-container || true
      
      - name: Verify Test Count From Report
        run: |
          echo "Analyzing test report from Docker run..."
          python3 scripts/verify_test_count.py 

  verify-collect:
    name: Verify Test Collection Against Baseline
    runs-on: ubuntu-latest
    needs: test-in-docker
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Build Test Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile.test
          tags: agent-data-test-local
          load: true
          platforms: linux/amd64
          provenance: false
          cache-from: type=gha
          cache-to: type=gha,mode=max
      
      - name: Generate Current Test Collection
        run: |
          echo "Generating current test collection for comparison..."
          docker run --rm agent-data-test-local pytest --collect-only -q --timeout=60 --override-ini="addopts=-m 'unit and not slow'" > current.txt
          wc -l current.txt
      
      - name: Verify Against Baseline
        run: |
          echo "Verifying test collection against baseline..."
          sha256sum -c .github/baseline_tests/collected_tests.sha256
          diff -q current.txt .github/baseline_tests/collected_tests.txt