name: CI and Push Image

on:
  push:
    branches: [test, main]
  pull_request:

permissions:
  contents: read
  id-token: write

jobs:
  test_fast:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: '3.11' }
      - run: pip install -r requirements.txt
      - run: pytest -m "unit and not slow"

  test_full_build_push:
    if: contains(fromJSON('["refs/heads/test", "refs/heads/main"]'), github.ref)
    needs: test_fast
    runs-on: ubuntu-latest
    concurrency:
      group: build-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@v4

      - uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_ID_PROVIDER }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}

      - uses: google-github-actions/setup-gcloud@v2
      - uses: docker/setup-buildx-action@v3

      - name: Build and Push multi-arch
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          provenance: true
          platforms: linux/amd64,linux/arm64
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: |
            asia-southeast1-docker.pkg.dev/github-chatgpt-ggcloud/agent-data/agent-data:latest
            asia-southeast1-docker.pkg.dev/github-chatgpt-ggcloud/agent-data/agent-data:${{ github.sha }}

      - name: Trivy security scan
        uses: aquasecurity/trivy-action@0.16.1
        with:
          image-ref: asia-southeast1-docker.pkg.dev/github-chatgpt-ggcloud/agent-data/agent-data:${{ github.sha }}
          severity: CRITICAL
          ignore-unfixed: true 