name: Debug Checkout Action

on:
  push:
    branches:
      - main

permissions:
  contents: read  # Grant read access to repository code

jobs:
  test-checkout:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: List files
        run: ls -la 