name: Deploy to Google Cloud Functions
# CLI153.2: Fixed CI for production deployment with proper secret validation
on:
  push:
    branches:
      - main
      - test
    paths:
      - 'functions/**'
      - '.github/workflows/deploy_functions.yaml'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Determine Project ID
        id: get_project
        run: |
          if [[ "${{ github.ref_name }}" == "main" ]]; then
            echo "project_id=${{ secrets.PROJECT_ID }}" >> $GITHUB_OUTPUT
          else
            echo "project_id=${{ secrets.PROJECT_ID_TEST }}" >> $GITHUB_OUTPUT
          fi

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}
          token_format: 'access_token'

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ steps.get_project.outputs.project_id }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Verify Authentication
        run: |
          echo "🔐 Verifying GCP authentication..."
          gcloud auth list --filter=status:ACTIVE --format="value(account)" | head -1
          echo "📋 Using project: ${{ steps.get_project.outputs.project_id }}"
          gcloud config set project ${{ steps.get_project.outputs.project_id }}

      - name: Deploy to Google Cloud Functions
        run: |
          set -e
          echo "🚀 Deploying Cloud Functions..."
          
          if [ ! -d "functions" ]; then
            echo "⚠️  No functions directory found, skipping deployment"
            exit 0
          fi
          
          for FUNCTION_DIR in $(find functions -mindepth 1 -maxdepth 1 -type d); do
            FUNCTION_NAME=$(basename "$FUNCTION_DIR")
            echo "📦 Deploying function: $FUNCTION_NAME"
            
            # Check if main.py exists
            if [ ! -f "$FUNCTION_DIR/main.py" ]; then
              echo "⚠️  No main.py found in $FUNCTION_DIR, skipping..."
              continue
            fi
            
            # Extract entry point from main.py
            ENTRY_POINT=$(grep -oP 'def \K\w+(?=\(.*\):)' "$FUNCTION_DIR/main.py" | head -n 1)
            if [ -z "$ENTRY_POINT" ]; then
              echo "⚠️  No entry point found in $FUNCTION_DIR/main.py, skipping..."
              continue
            fi
            
            echo "🎯 Entry point: $ENTRY_POINT"
            
            # Deploy function with retry logic
            for attempt in 1 2 3; do
              echo "🔄 Deployment attempt $attempt for $FUNCTION_NAME..."
              if gcloud functions deploy "$FUNCTION_NAME" \
                --region=asia-southeast1 \
                --runtime=python310 \
                --trigger-http \
                --allow-unauthenticated \
                --source="$FUNCTION_DIR" \
                --entry-point="$ENTRY_POINT" \
                --project=${{ steps.get_project.outputs.project_id }} \
                --memory=256MB \
                --timeout=60s; then
                echo "✅ Successfully deployed $FUNCTION_NAME"
                break
              else
                echo "❌ Deployment attempt $attempt failed for $FUNCTION_NAME"
                if [ $attempt -eq 3 ]; then
                  echo "❌ All deployment attempts failed for $FUNCTION_NAME"
                  exit 1
                fi
                sleep 10
              fi
            done
          done
          
          echo "🎉 All functions deployed successfully!"

      - name: Verify Deployments
        run: |
          echo "🔍 Verifying function deployments..."
          gcloud functions list --filter="name:*" --format="table(name,status,trigger.httpsTrigger.url)" --project=${{ steps.get_project.outputs.project_id }}
