name: Deploy Dummy Container

on:
  push:
    branches: [main, test]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_TEST }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Configure Docker to use gcloud
        run: gcloud auth configure-docker asia-southeast1-docker.pkg.dev

      - name: Build and push container
        run: |
          docker build -t asia-southeast1-docker.pkg.dev/${{ secrets.PROJECT_ID_TEST }}/agent-data/dummy-container:${{ github.sha }} containers/dummy_container
          docker push asia-southeast1-docker.pkg.dev/${{ secrets.PROJECT_ID_TEST }}/agent-data/dummy-container:${{ github.sha }}

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy dummy-container \
            --image=asia-southeast1-docker.pkg.dev/${{ secrets.PROJECT_ID_TEST }}/agent-data/dummy-container:${{ github.sha }} \
            --platform=managed \
            --region=asia-southeast1 \
            --allow-unauthenticated \
            --project=${{ secrets.PROJECT_ID_TEST }}

      - name: Verify deployment
        run: |
          echo "Dummy container deployed successfully"
          gcloud run services describe dummy-container --region=asia-southeast1 --project=${{ secrets.PROJECT_ID_TEST }} 