name: Deploy Containers

on:
  push:
    branches:
      - main
    paths:
      - 'containers/**'
  workflow_dispatch:

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Authenticate to Google Cloud (WIF)
      uses: google-github-actions/auth@v1
      with:
        workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
        service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}

    - name: Set up gcloud
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ secrets.PROJECT_ID }}

    - name: Configure Docker
      run: |
        gcloud auth configure-docker asia-southeast1-docker.pkg.dev --quiet

    - name: Build & Push Docker images
      run: |
        set -e
        for CONTAINER_DIR in $(find containers -mindepth 1 -maxdepth 1 -type d); do
          CONTAINER_NAME=$(basename "$CONTAINER_DIR")
          IMAGE="asia-southeast1-docker.pkg.dev/${{ secrets.PROJECT_ID }}/docker-repo/$CONTAINER_NAME:latest"

          echo "🔨 Building Docker image: $IMAGE"
          docker build -t "$IMAGE" "$CONTAINER_DIR"
          echo "🚀 Pushing Docker image: $IMAGE"
          docker push "$IMAGE"

          echo "📡 Deploying to Cloud Run: $CONTAINER_NAME"
          gcloud run deploy "$CONTAINER_NAME" \
            --image "$IMAGE" \
            --region asia-southeast1 \
            --platform managed \
            --allow-unauthenticated \
            --service-account=${{ secrets.GCP_SERVICE_ACCOUNT }}
        done