name: Deploy Cloud Workflows
# CLI153.2: Fixed CI for production deployment with proper secret validation

on:
  push:
    branches: [ "main", "test" ]
    paths:
      - 'workflows/**'
      - '.github/workflows/deploy_workflows.yaml'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GH_PAT }}
        submodules: 'recursive'

    - name: Determine Project ID
      id: get_project
      run: |
        if [[ "${{ github.ref_name }}" == "main" ]]; then
          echo "project_id=${{ secrets.PROJECT_ID }}" >> $GITHUB_OUTPUT
        else
          echo "project_id=${{ secrets.PROJECT_ID_TEST }}" >> $GITHUB_OUTPUT
        fi

    - name: Authenticate to Google Cloud (WIF)
      uses: google-github-actions/auth@v2
      with:
        workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
        service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}
        token_format: 'access_token'

    - name: Set up gcloud
      uses: google-github-actions/setup-gcloud@v2
      with:
        project_id: ${{ steps.get_project.outputs.project_id }}

    - name: Verify Authentication
      run: |
        echo "🔐 Verifying GCP authentication..."
        gcloud auth list --filter=status:ACTIVE --format="value(account)" | head -1
        echo "📋 Using project: ${{ steps.get_project.outputs.project_id }}"
        gcloud config set project ${{ steps.get_project.outputs.project_id }}

    - name: Deploy Cloud Workflows
      run: |
        set -e
        echo "🚀 Deploying Cloud Workflows..."
        
        if [ ! -d "workflows" ]; then
          echo "⚠️  No workflows directory found, skipping deployment"
          exit 0
        fi
        
        for WORKFLOW_FILE in $(find workflows -name "*.yaml" -o -name "*.yml"); do
          WORKFLOW_NAME=$(basename "$WORKFLOW_FILE" .yaml | sed 's/\\.yml$//')
          echo "📦 Processing workflow: $WORKFLOW_NAME"
          
          # Validate workflow file
          if [ ! -f "$WORKFLOW_FILE" ]; then
            echo "⚠️  Workflow file not found: $WORKFLOW_FILE, skipping..."
            continue
          fi
          
          # Check if workflow file is valid YAML
          if ! python3 -c "import yaml; yaml.safe_load(open('$WORKFLOW_FILE'))" 2>/dev/null; then
            echo "❌ Invalid YAML in $WORKFLOW_FILE, skipping..."
            continue
          fi
          
          # Deploy workflow with retry logic
          for attempt in 1 2 3; do
            echo "🔄 Deploy attempt $attempt for $WORKFLOW_NAME..."
            if gcloud workflows deploy "$WORKFLOW_NAME" \
              --source="$WORKFLOW_FILE" \
              --location=asia-southeast1 \
              --project=${{ steps.get_project.outputs.project_id }}; then
              echo "✅ Successfully deployed workflow $WORKFLOW_NAME"
              break
            else
              echo "❌ Deploy attempt $attempt failed for $WORKFLOW_NAME"
              if [ $attempt -eq 3 ]; then
                echo "❌ All deploy attempts failed for $WORKFLOW_NAME"
                exit 1
              fi
              sleep 10
            fi
          done
        done
        
        echo "🎉 All workflows deployed successfully!"

    - name: Verify Deployments
      run: |
        echo "🔍 Verifying Cloud Workflows deployments..."
        gcloud workflows list --format="table(name,state,createTime)" --project=${{ steps.get_project.outputs.project_id }}
