name: Deploy Workflows

on:
  push:
    branches: [ "test" ]
    paths:
      - 'workflows/**'
      - '.github/workflows/deploy_workflows.yaml'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Check if secrets are available
      id: check-secrets
      run: |
        if [ -z "${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}" ] || [ -z "${{ secrets.GCP_SERVICE_ACCOUNT }}" ]; then
          echo "::warning::Skipping deployment - GCP secrets not configured"
          echo "skip=true" >> $GITHUB_OUTPUT
        else
          echo "skip=false" >> $GITHUB_OUTPUT
        fi

    - name: Authenticate to Google Cloud (WIF)
      if: steps.check-secrets.outputs.skip != 'true'
      uses: google-github-actions/auth@v2
      with:
        workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
        service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}
        token_format: 'access_token'
        project_id: ${{ secrets.PROJECT_ID_TEST }}

    - name: Set up gcloud
      if: steps.check-secrets.outputs.skip != 'true'
      uses: google-github-actions/setup-gcloud@v2
      with:
        project_id: ${{ secrets.PROJECT_ID_TEST }}

    - name: Deploy Workflows
      if: steps.check-secrets.outputs.skip != 'true'
      run: |
        set -e
        for WORKFLOW_FILE in $(find workflows -name "*.yaml"); do
          WORKFLOW_NAME=$(basename "$WORKFLOW_FILE" .yaml)
          echo "Deploying workflow $WORKFLOW_NAME..."
          if ! gcloud workflows deploy "$WORKFLOW_NAME"             --source="$WORKFLOW_FILE"             --location=asia-southeast1; then
            echo "❌ Deployment failed for $WORKFLOW_NAME"
            exit 1
          fi
        done
