name: Deploy to Google Cloud

on:
  push:
    branches:
      - main
      - test
    paths:
      - 'functions/**'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set environment variables
        run: |
          if [ "${{ github.ref_name }}" == "main" ]; then
            echo "PROJECT_ID=${{ secrets.PROJECT_ID }}" >> $GITHUB_ENV
            echo "WORKLOAD_IDENTITY_PROVIDER=${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}" >> $GITHUB_ENV
            echo "SERVICE_ACCOUNT=${{ secrets.GCP_SERVICE_ACCOUNT }}" >> $GITHUB_ENV
          else
            echo "PROJECT_ID=${{ secrets.PROJECT_ID_TEST }}" >> $GITHUB_ENV
            echo "WORKLOAD_IDENTITY_PROVIDER=${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER_TEST }}" >> $GITHUB_ENV
            echo "SERVICE_ACCOUNT=${{ secrets.GCP_SERVICE_ACCOUNT_TEST }}" >> $GITHUB_ENV
          fi

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: ${{ env.WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ env.SERVICE_ACCOUNT }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Deploy to Google Cloud Functions
        run: |
          set -e
          for FUNCTION_DIR in $(find functions -mindepth 1 -maxdepth 1 -type d); do
            FUNCTION_NAME=$(basename "$FUNCTION_DIR")
            echo "Deploying $FUNCTION_NAME..."
            ENTRY_POINT=$(grep -oP 'def \K\w+(?=\(.*\):)' "$FUNCTION_DIR/main.py" | head -n 1)
            if ! gcloud functions deploy "$FUNCTION_NAME" \
              --region=asia-southeast1 \
              --runtime=python310 \
              --trigger-http \
              --allow-unauthenticated \
              --source="$FUNCTION_DIR" \
              --entry-point="$ENTRY_POINT" \
              --project=${{ env.PROJECT_ID }}; then
              echo "❌ Deployment failed for $FUNCTION_NAME"
              exit 1
            fi
          done