name: Deploy Containers

on:
  push:
    branches: [ "test" ]
    paths:
      - 'containers/**'
      - '.github/workflows/deploy_containers.yaml'
  workflow_dispatch: {}

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Check if secrets are available
      id: check-secrets
      run: |
        if [ -z "${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}" ] || [ -z "${{ secrets.GCP_SERVICE_ACCOUNT }}" ]; then
          echo "::warning::Skipping deployment - GCP secrets not configured"
          echo "skip=true" >> $GITHUB_OUTPUT
        else
          echo "skip=false" >> $GITHUB_OUTPUT
        fi

    - name: Authenticate to Google Cloud (WIF)
      if: steps.check-secrets.outputs.skip != 'true'
      uses: google-github-actions/auth@v2
      with:
        workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
        service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}
        token_format: 'access_token'
        project_id: ${{ secrets.PROJECT_ID_TEST }}

    - name: Set up gcloud
      if: steps.check-secrets.outputs.skip != 'true'
      uses: google-github-actions/setup-gcloud@v2
      with:
        project_id: ${{ secrets.PROJECT_ID_TEST }}

    - name: Create Artifact Registry repository
      if: steps.check-secrets.outputs.skip != 'true'
      run: |
        gcloud artifacts repositories create docker-repo \
          --repository-format=docker \
          --location=asia-southeast1 \
          --description="Docker repository for agent-data containers" \
          --project=${{ secrets.PROJECT_ID_TEST }} || echo "Repository already exists"

    - name: Configure Docker
      if: steps.check-secrets.outputs.skip != 'true'
      run: |
        gcloud auth configure-docker asia-southeast1-docker.pkg.dev --quiet

    - name: Build & Push Docker images
      if: steps.check-secrets.outputs.skip != 'true'
      run: |
        set -e
        for CONTAINER_DIR in $(find containers -mindepth 1 -maxdepth 1 -type d); do
          CONTAINER_NAME=$(basename "$CONTAINER_DIR")
          IMAGE="asia-southeast1-docker.pkg.dev/${{ secrets.PROJECT_ID_TEST }}/docker-repo/$CONTAINER_NAME:latest"

          echo "🔨 Building Docker image: $IMAGE"
          docker build -t "$IMAGE" "$CONTAINER_DIR"
          echo "🚀 Pushing Docker image: $IMAGE"
          docker push "$IMAGE"

          echo "📡 Deploying to Cloud Run: $CONTAINER_NAME"
          gcloud run deploy "$CONTAINER_NAME" \
            --image "$IMAGE" \
            --region asia-southeast1 \
            --platform managed \
            --allow-unauthenticated \
            --service-account=${{ secrets.GCP_SERVICE_ACCOUNT }}
        done
