name: Deploy Workflows

on:
  push:
    branches: [ "main", "test" ]
    paths:
      - 'workflows/**'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Authenticate to Google Cloud (WIF)
      uses: google-github-actions/auth@v1
      with:
        workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
        service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}

    - name: Set up gcloud
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ secrets.PROJECT_ID }}

    - name: Deploy Workflows
      run: |
        set -e
        for WORKFLOW_FILE in $(find workflows -name "*.yaml"); do
          WORKFLOW_NAME=$(basename "$WORKFLOW_FILE" .yaml)
          echo "Deploying workflow $WORKFLOW_NAME..."
          if ! gcloud workflows deploy "$WORKFLOW_NAME" \
            --source="$WORKFLOW_FILE" \
            --location=asia-southeast1; then  # Thay đổi location nếu cần
            echo "❌ Deployment failed for $WORKFLOW_NAME"
            exit 1
          fi
        done