name: Deploy Dummy Container

on:
  push:
    branches: [test]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check if secrets are available
        id: check-secrets
        run: |
          if [ -z "${{ secrets.GCP_SERVICE_ACCOUNT_TEST }}" ] || [ -z "${{ secrets.PROJECT_ID_TEST }}" ]; then
            echo "::warning::Skipping deployment - GCP secrets not configured"
            echo "skip=true" >> $GITHUB_OUTPUT
          else
            echo "skip=false" >> $GITHUB_OUTPUT
          fi

      - name: Authenticate to Google Cloud
        if: steps.check-secrets.outputs.skip != 'true'
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_TEST }}

      - name: Set up Cloud SDK
        if: steps.check-secrets.outputs.skip != 'true'
        uses: google-github-actions/setup-gcloud@v2

      - name: Create Artifact Registry repository
        if: steps.check-secrets.outputs.skip != 'true'
        run: |
          gcloud artifacts repositories create agent-data \
            --repository-format=docker \
            --location=asia-southeast1 \
            --description="Docker repository for agent-data project" \
            --project=${{ secrets.PROJECT_ID_TEST }} || echo "Repository already exists"

      - name: Configure Docker to use gcloud
        if: steps.check-secrets.outputs.skip != 'true'
        run: gcloud auth configure-docker asia-southeast1-docker.pkg.dev

      - name: Build and Push Docker Image
        if: steps.check-secrets.outputs.skip != 'true'
        run: |
          docker build -t asia-southeast1-docker.pkg.dev/${{ secrets.PROJECT_ID_TEST }}/agent-data/dummy-container:${{ github.sha }} containers/dummy_container
          docker push asia-southeast1-docker.pkg.dev/${{ secrets.PROJECT_ID_TEST }}/agent-data/dummy-container:${{ github.sha }}

      - name: Deploy to Cloud Run
        if: steps.check-secrets.outputs.skip != 'true'
        run: |
          gcloud run deploy dummy-container \
            --image=asia-southeast1-docker.pkg.dev/${{ secrets.PROJECT_ID_TEST }}/agent-data/dummy-container:${{ github.sha }} \
            --platform=managed \
            --region=asia-southeast1 \
            --allow-unauthenticated \
            --project=${{ secrets.PROJECT_ID_TEST }}

      - name: Verify deployment
        if: steps.check-secrets.outputs.skip != 'true'
        run: |
          echo "Dummy container deployed successfully"
          gcloud run services describe dummy-container --region=asia-southeast1 --project=${{ secrets.PROJECT_ID_TEST }}
