name: CI/CD Deployment

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Deploy to Google Cloud
      env:
        GOOGLE_CLOUD_PROJECT: ${{ secrets.GOOGLE_CLOUD_PROJECT }}
        GOOGLE_CLOUD_SERVICE_KEY: ${{ secrets.GOOGLE_CLOUD_SERVICE_KEY }}
      run: |
        echo "${{ secrets.GOOGLE_CLOUD_SERVICE_KEY }}" > gcloud-key.json
        gcloud auth activate-service-account --key-file=gcloud-key.json
        gcloud functions deploy google_docs_updater \
          --runtime python310 \
          --trigger-http \
          --allow-unauthenticated \
          --source=. \
          --region=us-central1 \
          --project=${{ secrets.GOOGLE_CLOUD_PROJECT }} \
          --timeout=300s

