name: Nightly CI
on:
  schedule:
    - cron: '0 18 * * *'
  workflow_dispatch:
  push:
    branches: [ test ]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run tests
        run: pytest --collect-only -q | grep -c "::test_" > test_count.txt
      - name: Verify test count
        run: |
          count=$(cat test_count.txt)
          if [ "$count" -ne 481 ]; then
            echo "Test count $count does not match expected 481"
            exit 1
          fi
