name: Run Slow Tests

on:
  schedule:
    - cron: "0 3 * * 1" # Run every Monday at 3:00 AM UTC
  workflow_dispatch: # Allows manual triggering

jobs:
  run-slow-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.11" # Specify your project's Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest

      - name: Run slow tests
        run: pytest -m slow

      - name: Notify on failure
        if: failure()
        run: |
          echo "Slow tests failed!"
          # Replace with your preferred notification method, e.g., creating a GitHub issue
          # curl --request POST \
          # --url https://api.github.com/repos/${{ github.repository }}/issues \
          # --header "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
          # --header "Content-Type: application/json" \
          # --data '{
          #   "title": "Slow tests failed on ${{ github.ref_name }}",
          #   "body": "The workflow for running slow tests failed. Please check the logs: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          # }'
          echo "Workflow URL: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
